# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vivado_work/Nexys4DDR_Master.xdc

# Block Designs: bd/helloworldip/helloworldip.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip || ORIG_REF_NAME==helloworldip} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_microblaze_0_0/helloworldip_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_microblaze_0_0 || ORIG_REF_NAME==helloworldip_microblaze_0_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_microblaze_0_axi_periph_0/helloworldip_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_microblaze_0_axi_periph_0 || ORIG_REF_NAME==helloworldip_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_mdm_1_0/helloworldip_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_mdm_1_0 || ORIG_REF_NAME==helloworldip_mdm_1_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_clk_wiz_1_0/helloworldip_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_clk_wiz_1_0 || ORIG_REF_NAME==helloworldip_clk_wiz_1_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_rst_clk_wiz_1_100M_0/helloworldip_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==helloworldip_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_axi_uartlite_0_0/helloworldip_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_axi_uartlite_0_0 || ORIG_REF_NAME==helloworldip_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_mig_7series_0_0_1/helloworldip_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_mig_7series_0_0 || ORIG_REF_NAME==helloworldip_mig_7series_0_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_rst_mig_7series_0_81M_1/helloworldip_rst_mig_7series_0_81M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_rst_mig_7series_0_81M_1 || ORIG_REF_NAME==helloworldip_rst_mig_7series_0_81M_1} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_xbar_0/helloworldip_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_xbar_0 || ORIG_REF_NAME==helloworldip_xbar_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_dlmb_v10_0/helloworldip_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_dlmb_v10_0 || ORIG_REF_NAME==helloworldip_dlmb_v10_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_ilmb_v10_0/helloworldip_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_ilmb_v10_0 || ORIG_REF_NAME==helloworldip_ilmb_v10_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_dlmb_bram_if_cntlr_0/helloworldip_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==helloworldip_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_ilmb_bram_if_cntlr_0/helloworldip_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==helloworldip_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_lmb_bram_0/helloworldip_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_lmb_bram_0 || ORIG_REF_NAME==helloworldip_lmb_bram_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_auto_cc_0/helloworldip_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_auto_cc_0 || ORIG_REF_NAME==helloworldip_auto_cc_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_auto_pc_0/helloworldip_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_auto_pc_0 || ORIG_REF_NAME==helloworldip_auto_pc_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_auto_ds_1/helloworldip_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_auto_ds_1 || ORIG_REF_NAME==helloworldip_auto_ds_1} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_auto_ds_0/helloworldip_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_auto_ds_0 || ORIG_REF_NAME==helloworldip_auto_ds_0} -quiet] -quiet

# IP: bd/helloworldip/ip/helloworldip_auto_us_0/helloworldip_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==helloworldip_auto_us_0 || ORIG_REF_NAME==helloworldip_auto_us_0} -quiet] -quiet

# XDC: bd/helloworldip/helloworldip_ooc.xdc
